flask_app/landlords/routes.py
from flask import Blueprint, render_template, redirect, request
from ..forms import LandlordReviewForm, CurrentLandlordReviewForm
from ..models import LandlordReview
from flask_login import current_user
import numpy as np #use np to find unique values of list

landlords = Blueprint("landlords", __name__)

@landlords.route("/", methods=["GET", "POST"])
def index():
    form = LandlordReviewForm()
    reviews = LandlordReview.objects()

    if form.validate_on_submit():
        review = LandlordReview(
            author = form.name.data,
            landlord_name = form.landlordName.data,
            location = form.address.data,
            rating = form.rating.data,
            review_content = form.landlordReview.data,
            landlord_id = form.landlordName.data.replace(" ", ""))

        review.save()
        return redirect(request.path)
  
    return render_template("index.html", form = form, current_user = current_user, reviews = reviews)

@landlords.route('/landlords/<landlord_id>', methods = ["GET", "POST"])
def landlord(landlord_id):

    form = CurrentLandlordReviewForm()
    #if landlord_name not in database, display a message
    if not LandlordReview.objects(landlord_id = landlord_id):
        return render_template("index.html")
    
    reviews = LandlordReview.objects(landlord_id=landlord_id)
    review = reviews.first()
    landlord_name = review.landlord_name
    if form.validate_on_submit():
        review = LandlordReview(
            author = form.name.data,
            landlord_name = landlord_name,
            location = form.address.data,
            rating = form.rating.data,
            review_content = form.landlordReview.data,
            landlord_id = form.landlordName.data.replace(" ", ""))

        review.save()
        return redirect(request.path)

    return render_template("landlord.html", reviews=reviews, landlord_name = landlord_name, form = form, current_user = current_user)

#display a list of all of the landlords in the database
@landlords.route('/landlords', methods = ["GET", "POST"])
def landlords_index():

    reviews = LandlordReview.objects()
    landlord_ids = []
    landlord_names = []
    
    for review in reviews:
        landlord_ids.append(review.landlord_id)
        landlord_names.append(review.landlord_name)

    landlord_ids = list(np.unique(landlord_ids))
    landlord_names = list(np.unique(landlord_names))

    landlords = []
    for i in range(len(landlord_ids)):
        landlords.append((landlord_names[i], landlord_ids[i]))


    #for each id, get all the review ratings for that id

    return render_template("landlords_index.html", landlords=landlords,  current_user = current_user)

@landlords.route('/about', methods = ["GET", "POST"])
def about():
    form = LandlordReviewForm()
 
    return render_template('about.html')

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegisterForm, LoginForm, UpdatePasswordForm, UpdateUsernameForm
from ..models import User

users = Blueprint("users", __name__)

#TODO:
#add more strict password requirements as discussed in specifications
#account html template has to to be fixed, only want to let them change their password or username

@users.route('/users/<username>', methods=['GET', 'POST'])
@login_required
def account(username):
    username_form = UpdateUsernameForm()
    password_form = UpdatePasswordForm()

    if username_form.validate_on_submit():
        print(current_user.username)
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for('users.account', username=current_user.username))

    if password_form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(password_form.password.data).decode("utf-8")
        current_user.modify(password=hashed)
        current_user.save()
        return redirect(url_for('users.account', username=current_user.username))

    return render_template('account.html', username_form=username_form, password_form=password_form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('landlords.index'))
    
    form = LoginForm()
    errors = ""
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        print("entering form validation")
        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            print("here")
            login_user(user)
            return redirect(url_for('users.account', username=form.username.data))
        else:
            flash("Login Failed. Make sure you entered the right username/password")
            errors = "Login Failed. Make sure you entered the right username/password"
            print("errors is being updated to ", errors)
    return render_template('login.html', form=form, errors=errors)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index"))

    form = RegisterForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))


    return render_template('register.html', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('landlords.index'))

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}
<h3>About Us</h3>
<ps style="font-size: 20px">
    Thanks for visiting RateMyUMDLandlord. This flask app was created by Surmud Jamil, Aashray Raparla, and Eric Qian, for the final project of our python flask development class, CMSC388J, at the University of Maryland. 
    This website allows UMD students to find landlords within the College Park area, rate landlords on a scale from 1-5, and write comments about a specific landlord. 
    With this website, we hope that we can help people looking for housing near the College Park area get a better understanding of their landlords. We understand that it can be frustrating to 
    find out that your landlord isn’t a very nice person, and we hope we can help you make a more informed decision and choose the best place to live. 
    <br />
    <br />
    <h5>Surmud Jamil</h5>
    My name is Surmud Jamil and I'm a junior at UMD. I was able to come up with the idea for this app because I ended up dealing with a landlord who wasn't very good, and I wanted there to be a way for people
    around UMD to know what their landlord is like before signing a lease.
    As a student pursuing data science and software engineering, I've had the experience of teaching coding to kids and teenagers in the past, which I've really enjoyed. After my internship this summer, 
    I hope I can find a job next year relating to data science and machine learning, which are the things that I enjoy the most in computer science. If you'd like to check out my github, you can view my other projects
    at github.com/surmud.
    <br />
    <br />
    <h5>Aashray Raparla</h5>
    Hi, my name is Aashray Raparla. I am currently a sophomore at the University of Maryland, College Park majoring in Computer Science and minoring in innovation and 
    entrepreneurship. I am interested in Web Development and have been working with different Frontend and backend frameworks to help build my skills. I hope to also minor
    in Statistics and leave this class with a good understanding of Flask and building web apps with Flask. 

    <br />
    <br />
    <h5>Eric Qian</h5>
    Hi, my name is Eric Qian. I am currently a junior at the University of Maryland, College Park majoring in computer science and minoring in innovation and entrepreneurship.
    A project I’ve worked on by myself is an Amazon web scraper that you can find on my github under the personal repository. The web scraper allows the user to input any Amazon
    product page and it will grab the contents and store it neatly in a CSV file. What motivated me to make this was to make the shopping experience on Amazon a little easier 
    and faster. Browsing through Amazon can take a long time, especially if there are a lot of products, so this web scraper just grabs the pertinent information that you will
    most likely need. Information that is grabbed includes the name of the product, the price, and the link to the product if you want to buy it. It does all this in seconds,
    while browsing through Amazon would normally take minutes. As you can see, I enjoy creating things to help people and make their lives easier. There is still a lot to 
    learn and a lot more things that I want to do. 
    

  </p>
 
{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="col d-flex justify-content-center">
    <h4>Hello {{ current_user.username }}</h4>
</div>
<div class="mt-4">
  <h3>Update your Username</h3>
</div>
<div class="row">
  <div class="col">
      <form action="" method="post">
          {{ username_form.csrf_token }}
          <div class="form-group">
              {{ username_form.username.label(class="form-control-label") }}
              {{ username_form.username(class="form-control form-control-lg") }}

              {% if username_form.username.errors %}
              <div class="alert alert-warning" role="alert">
                  {% for error in username_form.username.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
              </div>
              {% endif %}
          </div>
          <div class="form-group">
              {{ username_form.submit }}
          </div>
      </form>
  </div>
</div>
<div class="mt-4">
  <h3>Update your Password</h3>
</div>
<div class="row">
  <div class="col">
      <form action="" method="post">
          {{ password_form.csrf_token }}
          <div class="form-group">
              {{ password_form.password.label(class="form-control-label") }}
              {{ password_form.password(class="form-control form-control-lg") }}

              {% if password_form.password.errors %}
              <div class="alert alert-warning" role="alert">
                  {% for error in password_form.password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
              </div>
              {% endif %}
          </div>
          <div class="form-group">
              {{ password_form.submit }}
          </div>
      </form>
  </div>
</div>
{#<div class="row">
    <div class="col">
        <a href="{{ url_for('user_detail') }}"> User Details </a>
    </div>
</div>#}
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>RateMyUMDLandlord</title>
    {% endif %}
</head>
<body>
    {% block header %}
    
    <h1>Overrideable Content</h1>
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}

<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <img class = "propic" src="../static/testudo.png" alt="pic1"> 
    <a class="navbar-brand" href="{{ url_for('landlords.index') }}">RateMyUMDLandlord</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
      
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('landlords.index')}}">
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('landlords.landlords_index')}}">
                    Landlords Index
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('landlords.about') }}">
                    About
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account', username = current_user.username)}}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>

            {% endif %}
            
        </ul>
    </div>

    
</nav>


<div class="container">
    
    {% block content %}{% endblock %}
</div>

{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}


<div class="jumbotron">
    <h1 class="display-4">Welcome to Rate My UMD Landlord! </h1>
    <p class="lead">This is a simple website that allows students to rate and review landlords from College Park, Maryland. This web application
      was created by Surmud Jamil, Aashray Raparla, and Eric Qian, as a final project for CMSC388J at the University of Maryland. This project
      was made using the Flask framework in Python. To learn more about us, see our About page.
    </p>
    <hr class="my-4">
    {% if not current_user.is_authenticated %}
    <p style="font-size:18px;">To leave a review, go ahead and register with us.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Register</a>
      <p style="font-size:18px;">Already have an account? Log in below to get started! </p>
      <a class="btn btn-primary btn-lg" href="{{ url_for('users.login') }}" role="button">Log In</a>
    </p>
    
   
    {%else %}
    <p>Welcome back, you are logged in! Go ahead and leave a review below.</p>
    {%endif%}
  </div>




<section>
  <style>
    hr {
      margin-top: 2rem;
      margin-bottom: 1rem;
      border: 0;
      border-top: 7px solid rgba(7, 0, 0, 0.1);
      padding-top: 0%;
      padding-bottom: 0%;
    }
  
  #container { 
      display: flex;
      background-color:
      I#f9f9f969;
      border-radius: 0px;
      width: 100%;
      height: 120px;
      flex-direction: row;
      align-content: center;
  }
  #landlord {
      font-family: Arial, Helvetica, sans-serif;
      padding-left: 0%;
      padding-top: 0%;
      align-items: center;
      flex-direction: column;
      width: 220px;
      height: 100px;
  }
  #review {
      font-family: Arial, Helvetica, sans-serif;
      padding-top: 0%;
      padding-right: 10%;
      padding-left : 10%;
      padding-bottom: 10%;
      display: flex;
      align-items: left;
      justify-content: left;
      width: 700px;
      height: 100px;
  
  }
  

  
  </style>
  
  <h2> Recent Landlord Reviews</h2>
  <hr>
  {%for review in reviews%}
  <div class="media">
    <div class="media-body">
      <div id = "container">
        <div id = "landlord">
          
          <a href="{{ url_for('landlords.landlord', landlord_id = review.landlord_id) }}" ><h3>{{review.landlord_name}}</h3></a>
          
          <p>Location: {{review.location}} <br> Rating: {{review.rating}}/5 <br> Posted By: {{review.author}}</p>
        </div>
        <div id ="review">
          <p> {{review.review_content}}
        </div>
      </div>
      
    </div>
  </div>
  <hr>
  <br>
  {%endfor%}
  
  {% if current_user.is_authenticated %}
  <h3>Leave Your Review</h3>
  <form action="" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.landlordName.label(class="form-control-label green-text") }}
      {{ form.landlordName(class="form-control form-control-md") }}
  
      {% if form.landlordName.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form.landlordName.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.name.label(class="form-control-label green-text") }}
      {{ form.name(class="form-control form-control-md") }}
  
      {% if form.name.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form.password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.address.label(class="form-control-label green-text") }}
      {{ form.address(class="form-control form-control-md") }}
  
      {% if form.address.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form.address.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.landlordReview.label(class="form-control-label green-text") }}
      {{ form.landlordReview(class="form-control form-control-md") }}
  
      {% if form.landlordReview.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form.landlordReview.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  
    <div class="form-group">
      {{ form.rating.label(class="form-control-label green-text") }}
      {{ form.rating(class="form-control form-control-md") }}
  
      {% if form.rating.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form.rating.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  
  
  
    {% if errors|length > 0 %}
    <div class="alert alert-warning" role="alert">
      {{ errors }}
    </div>
    {% endif %}
    <div class="form-group">
      {{ form.submit(class="form-control form-control-lg") }}
    </div>
    <!-- <button type="submit" class="btn btn-primary">Register Now</button> -->
  </form>
  
</section>


{%else%}
<ps style="font-size: 20px"><img class = "propic" src="../static/testudo_copy.png" alt="pic2"> Want to leave your own review? Go ahead and create an account with us!</ps>
{%endif%}
{% endblock %}

flask_app/templates/landlord.html
{% extends "header.html" %}
{% block content %}
</style>
<h2>Landlord Reviews For {{landlord_name}}</h2>
<hr>
{%for review in reviews%}
<div class="media">
  <div class="media-body">
    <div id = "container">
      <div id = "landlord">
        <h3>{{review.landlord_name}}</h3>
        <p>Location: {{review.location}} <br> Rating: {{review.rating}}/5 <br> Posted By: {{review.author}}</p>
      </div>
      <div id ="review">
        <p> <i>{{review.review_content}}</i>
      </div>
    </div>
    
  </div>
</div>
<hr>
<br>
{%endfor%}
{% if current_user.is_authenticated %}
<h3>Leave Your Review for {{landlord_name}}!</h3>
<form action="" method="POST">
  {{form.csrf_token }}
  <div class="form-group">
    {{ form.name.label(class="form-control-label") }}
    {{ form.name(class="form-control form-control-md") }}

    {% if form.name.errors %}
    <div class="alert alert-warning" role="alert">
      {% for error in form.password.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.address.label(class="form-control-label green-text") }}
    {{ form.address(class="form-control form-control-md") }}

    {% if form.address.errors %}
    <div class="alert alert-warning" role="alert">
      {% for error in form.address.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.landlordReview.label(class="form-control-label green-text") }}
    {{ form.landlordReview(class="form-control form-control-md") }}

    {% if form.landlordReview.errors %}
    <div class="alert alert-warning" role="alert">
      {% for error in form.landlordReview.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% endif %}
  </div>

  <div class="form-group">
    {{ form.rating.label(class="form-control-label green-text") }}
    {{ form.rating(class="form-control form-control-md") }}

    {% if form.rating.errors %}
    <div class="alert alert-warning" role="alert">
      {% for error in form.rating.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% endif %}
  </div>



  {% if errors|length > 0 %}
  <div class="alert alert-warning" role="alert">
    {{ errors }}
  </div>
  {% endif %}
  <div class="form-group">
    {{ form.submit(class="form-control form-control-lg") }}
  </div>
  <!-- <button type="submit" class="btn btn-primary">Register Now</button> -->
</form>
</section>

{%else%}
<p style="font-size:18px;">Want to leave your review for {{landlord_name}}? Log in below to get started! </p>
      <a class="btn btn-primary btn-lg" href="{{ url_for('users.login') }}" role="button">Log In</a>
      <hr>
      <p style="font-size:18px;">Don't have an account yet? Just register below!</p>
      <a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Register</a>
{%endif%}
{% endblock content %}

flask_app/templates/landlords_index.html
{% extends "header.html" %}
{% block content %}
<h3>Landlords Index</h3>
<p class="lead">This is a comprehensive list of all landlords in our database. Click on a landlord's name to see all of their reviews!</p>
{%for name, id in landlords%}
<hr>
<a href="{{ url_for('landlords.landlord', landlord_id = id) }}" ><h4>{{name}}</h4></a>
{%endfor%}


{% endblock content %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
  <div class="col">
    <h2>Log In</h2>
    <form action="" method="POST">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.username.label(class="form-control-label green-text") }}
        {{ form.username(class="form-control form-control-md") }}
  
        {% if form.username.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {{ form.password(class="form-control form-control-lg") }}
  
        {% if form.password.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      {% if errors|length > 0 %}
      <div class="alert alert-warning" role="alert">
        {{ errors }}
      </div>
      {% endif %}
      <div class="form-group">
        {{ form.submit(class="form-control form-control-lg") }}
      </div>
      <!-- <button type="submit" class="btn btn-primary">Register Now</button> -->
    </form>
  </div>
</div>
<div class="row">
  <div class="col">
    <h6> Don't have an account? Click <a href="{{ url_for('users.register') }}"> here </a> to register an account. </h6>
    
  </div>
</div>
<div class="row">
  <div class="col">
    {% if current_user.is_authenticated %}
    <h1> Welcome {{ current_user.username }}! </h1>
    {%endif %}
    
  </div>
  
</div>
{% endblock %}

flask_app/templates/movie_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if movie %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ movie.title }} ({{ movie.year }})
      </div>
      <div class="card-body">
        <img src="{{ movie.poster_url }}" class="mr-3 movie" alt="alt text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Directed by:</b> {{ movie.director }}</li>
          <li class="list-group-item"><b>Actors:</b> {{ movie.actors }}</li>
          <li class="list-group-item"><b>Genres:</b> {{ movie.genres }}</li>
          <li class="list-group-item"><b>Awards:</b> {{ movie.awards }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <img class="mr-3 comment-pic" src="data:image/png;base64,{{review.image}}" alt="">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2 class="text-center">Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
      <h6 class="text-center"><a href="{{ url_for('users.login')}}">Login</a> if you already have an account. </h6>
        {# Ask the user to login if they already have an account #}
    </div>
</div>
<!-- Registration Form: -->
    <div class="col">
      {% if current_user.is_authenticated %}
        <h1 class="text-center"> Welcome {{ current_user.username }}! </h1>
        {%endif %}
    </div>
    <form action="" method="post">
      {{ form.csrf_token }}
      <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {{ form.username(class="form-control form-control-lg") }}
          {% if form.username.errors %}
          <div class="alert alert-warning" role="alert">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% endif %}
      </div>
      <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {{ form.email(class="form-control form-control-lg") }}
          {% if form.email.errors %}
          <div class="alert alert-warning" role="alert">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% endif %}
      </div>
      <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {{ form.password(class="form-control form-control-lg") }}
          {% if form.password.errors %}
          <div class="alert alert-warning" role="alert">
              {% for error in form.password.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% endif %}
      </div>
      <div class="form-group">
          {{ form.confirm_password.label(class="form-control-label") }}
          {{ form.confirm_password(class="form-control form-control-lg") }}
          {% if form.confirm_password.errors %}
          <div class="alert alert-warning" role="alert">
              {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% endif %}
      </div>
      <div class="form-group">
          {{ form.submit(class="form-control form-control-lg") }}
      </div>
  </form>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
      {% if current_user is None %}
        <h2> Error: User does not exist </h2>
        {# Display any error messages #}
    </div>
</div>
<div class="row">
    <div class="col">
        {# User's Profile Picture #}
        
    </div>
    <div class="col">
      {{ current_user }}
        {# Indicate which user's reviews we're looking at #}
    </div>
</div>
<div class="row">
    <div class="col">
      {% for review in reviews %}
        {{ review }}
        {# Show all reviews made by the user #}
    </div>
</div>
{% endblock %}